package co.zecko.retailer.common.enums;

public enum InventoryUnitEvent {
    REQUEST_CANCELLATION,

    SHIP,

    CANCEL_CANCELLATION_REQUEST,
    APPROVE_CANCELLATION_REQUEST,

    MARK_OUT_FOR_DELIVERY,

    DELIVER,
    MARK_FAILED_DELIVERY,

    REQUEST_RETURN,
    REQUEST_EXCHANGE,

    CANCEL_RETURN,
    APPROVE_RETURN_REQUEST,

    MARK_OUT_FOR_PICKUP,

    PICK_UP,
    MARK_FAILED_PICKUP,

    DELIVER_TO_BRAND,

    APPROVE_EXCHANGE_REQUEST,
    CANCEL_EXCHANGE,

    INITIATE_REFUND
}
